### ISSUE TITLE
App is installed but set on pause?

### ISSUE THREAD

**Issue by Tequila329** [balmli/com.lametric.time#1]
Hi,

First of all --> cool to have a app again for the Lametric devices :) 

I installed the app via CLI, the app is activated but set on pause mode? Could not add a new device.

**Comment by balmli** [comment]
It only works for SDK3 .. for firmware 5.0.0

**Comment by Tequila329** [comment]
Sure, I'm on 5.0.0 RC34

**Comment by balmli** [comment]
OK, thanks! 

I will check.

**Comment by Tequila329** [comment]
![42DECF43-8007-4B28-BD37-05803CCA63B4](https://user-images.githubusercontent.com/47381420/95683346-fecc8080-0bea-11eb-95ba-52810d80c83e.png)
![6D7499B9-7D42-4502-B003-0B4C4562443D](https://user-images.githubusercontent.com/47381420/95683349-fffdad80-0bea-11eb-976c-6e94bd6e5f7d.png)

**Comment by balmli** [comment]
Can you "run" the app, and send the log.

homey app run

**Comment by Tequila329** [comment]
Warning: Trying to access `Homey.env.CLIENT_ID` but the environment variable has not been set!
Warning: Trying to access `Homey.env.CLIENT_SECRET` but the environment variable has not been set!
Unable to initialize app OAuth2Error: Invalid Client ID
    at LametricTimeApp.setOAuth2Config (/node_modules/homey-oauth2app/lib/OAuth2App.js:75:13)
    at LametricTimeApp.onOAuth2Init (/app.js:11:14)
    at LametricTimeApp.onInit (/node_modules/homey-oauth2app/lib/OAuth2App.js:21:17)
    at SDK._initApp (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:284:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SDK.createClient (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:172:5)

--- INFO: com.lametric.time has been killed ---

**Comment by balmli** [comment]
Yes, the `env.json` - file is missing.

**Comment by Tequila329** [comment]
Was it missing in the repository or was it a mistake by me during installation?

**Comment by balmli** [comment]
It's not supposed to be checked in the repository.  Also no mistake be you.

**Comment by balmli** [comment]
I sent you the content of the file in the Homey Community Forum
