### ISSUE TITLE
Repair device option kills the Homey app

### ISSUE THREAD

**Issue by Tequila329** [balmli/com.lametric.time#2]
If I try to use the repair function, i get the LaMetric login screen, but when it shows "Success! You can close the window" and you click on "close" the Homey app crashes.

**Comment by balmli** [comment]
Yes, I've seen that.  

Must be a bug in the Homey app.

**Comment by balmli** [comment]
Athom has confirmed that this is a bug in the Homey mobile app, and that they will fix it in a later release of the app.
