### ISSUE TITLE
Not all icons loaded

### ISSUE THREAD

**Issue by eelkemooij** [balmli/com.lametric.time#5]
Not all icons are loaded. I have only 2304 icons available. Waiting for a few minutes after starting the app doesn't help.
Is it somehow possible to put the icon ID in the inputbox if it is not cached? 

Thanks for revival and improvements of the app!! 👍

**Comment by pro-sumer** [comment]
Same issue here. Ends exactly at 2304, but I want to use 2659 (mailbox) and 5453 (bell).

Any way to do this manually? (Via developer website, SSH, or ...?)

**Comment by balmli** [comment]
Check v. 1.2.0
https://homey.app/a/com.lametric.time/test/

More info here:
https://community.athom.com/t/app-lametric/36868/13
