### ISSUE TITLE
Version 1.1.0 don't work on my Homey device

### ISSUE THREAD

**Issue by paveldn** [balmli/com.lametric.time#6]
Version 0.9.2 worked OK but after update to 1.1.0 it is crashing on startup. My homey is running on latest test version of 5.0 firmware.
Here is the logs:
[32mтЬУ Pre-processing app...[39m
[32mтЬУ Running plugins...[39m
[32mтЬУ Running plugin `compose`...[39m
[90m[AppPluginCompose] Added FlowCard `alarm_enable` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `alarm_set` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `clear_notification_queue` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `clock_face` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `clock_face_custom` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `next_widget` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `notificationText` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `notificationTextIcon` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `notificationTextIconSound` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `notificationTextSound` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `prev_widget` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `radio` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `set_brightness` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `set_brightness_auto` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `show_widget` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `stopwatch` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `timer` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `timer_set` for type `actions`[39m
[90m[AppPluginCompose] Added FlowCard `weather` for type `actions`[39m
[90m[AppPluginCompose] Added Driver `lametric`[39m
[32mтЬУ Plugin `compose` finished[39m
[32mтЬУ Running plugin `oauth2`...[39m
[32mтЬУ Installing npm package (homey-oauth2app)[39m
[32mтЬУ Installation complete[39m
[32mтЬУ Plugin `oauth2` finished[39m
[32mтЬУ Validating app...[39m
[32mтЬУ Homey App validated successfully against level `debug`[39m
[32mтЬУ Packing Homey App...[39m
[32mтЬУ Pruning dev dependencies...[39m
[90m тАФ App size: 471 KB[39m
[32mтЬУ Installing Homey App on `Homey` (http://*.*.*.*:80)...[39m
[32mтЬУ Homey App `com.lametric.time` successfully installed[39m
[32mтЬУ Running `com.lametric.time`, press CTRL+C to quit[39m
[90m тАФ Profile your app's performance at https://go.athom.com/app-profiling?homey=5ad4ab43a607c525f40e2cdc&app=com.lametric.time[39m
тФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФА Logging stdout & stderr тФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФА
Warning: Trying to access `Homey.env.CLIENT_ID` but the environment variable has not been set!
Warning: Trying to access `Homey.env.CLIENT_SECRET` but the environment variable has not been set!

--- INFO: com.lametric.time has been killed ---
тФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФАтФА
[32mтЬУ Uninstalling `com.lametric.time`...[39m
[32mтЬУ Homey App `com.lametric.time` successfully uninstalled[39m

**Comment by balmli** [comment]
Hi,

You're missing a env.json file with CLIENT_ID and CLIENT_SECRET.   You can create this, or install from the Homey Community Store:

https://store.homey.community/app/com.lametric.time

**Comment by paveldn** [comment]
It was the version from the community store. The test version from the official store actually works. fine. Thank!
